name: 'Hexo GitHub Action'
description: 'A GitHub action used to automatic generate and deploy hexo-based blog.'
author: 'yrpang'
branding:
  icon: upload-cloud
  color: green
inputs:
  deploykey:
    description: 'The develop key of your GitHub Page repository'
    required: true
  username:
    description: 'Your user name'
    required: true
  email:
    description: 'Your email address'
    required: true
  if_update_files:
    description: 'Whether update the source file after generate'
    required: false
    default: false
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: false
    default: ''
  branch:
    description: 'The branch of the blog source code'
    required: false
    default: 'master'
  if_update_cloudflare:
    description: 'Whether update cloudflare'
    required: false
    default: false
  cloudflare_token: 
    description: 'Your cloudflare api key'
    required: false
  cloudflare_zone:
    description: 'the cloudflare zone'
    required: false
  cloudflare_username:
    description: 'Your cloudflare user name'
    required: false
  purge_list:
    description: 'purge list'
    required: false
  
runs:
  using: 'docker'
  image: 'Dockerfile'
